version: '3.8'
services:
  backend:
    depends_on:
      - db
      - minio
    build: .
    env_file:
      - .env
      - .env.docker
    ports:
      - ${PORT}:3000
  db:
    image: postgres:14.1-alpine
    restart: no
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${APP_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_storage:/var/lib/postgresql/data
  db-test:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
      - .env.example
    environment:
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${TEST_POSTGRES_PORT}:5432'
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

volumes:
  db_storage:
    driver: local
  minio_storage:
    driver: local
