### Create Drone
POST {{host}}/drones
Content-Type: application/json

{
  "serialNumber": "1234 lol",
  "weightLimit": 500,
  "state": "IDLE",
  "model": "Lightweight",
  "batteryCapacity": 90
}


### List available drones
GET {{host}}/drones

### Get battery level of a single drone
GET {{host}}/drones/d007a1a6-d685-4837-8704-4750e3f80c27/battery

### Load item
PATCH {{host}}/drones/81c0fbdd-c7c6-42d4-b5a6-ea8ffa647e00/items/b7ad918d-edae-4b3d-97e3-ceb669a73b71
