### Create Drone
POST {{host}}/drones
Content-Type: application/json

{
  "serialNumber": "1234 lol",
  "weightLimit": 500,
  "state": "IDLE",
  "model": "Lightweight",
  "batteryCapacity": 90
}


### List available drones
GET {{host}}/drones

### Get battery level of a single drone
GET {{host}}/drones/2e6bf707-6ff3-4e44-84e5-3aba43cbab98/battery

### Load item
PATCH {{host}}/drones/973c4eb9-2edc-4631-a140-29d42f1f158d/items/load/d42eb3e1-6298-47d0-8ebf-3bb2b907ae89
