### Create Medicament
POST {{host}}/medicaments
Content-Type: application/json

{
  "code": "VCT",
  "image": "picsum/2",
  "name": "Victorious45",
  "weight": 35
}

### List Medicaments
GET {{host}}/medicaments
