export enum EnvVars {
  MINIO_ROOT_USER = 'MINIO_ROOT_USER',
  MINIO_ROOT_PASSWORD = 'MINIO_ROOT_PASSWORD',
  MINIO_HOST = 'MINIO_HOST',
  MINIO_PORT = 'MINIO_PORT',
  MINIO_BUCKET = 'MINIO_BUCKET',
  TEST_S3_BUCKET = 'TEST_S3_BUCKET',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  TEST_POSTGRES_HOST = 'TEST_POSTGRES_HOST',
  TEST_POSTGRES_PORT = 'TEST_POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  APP_DB = 'APP_DB',
  TEST_DB = 'TEST_DB',
  PORT = 'PORT'
}
